### ISSUE TITLE
Failing to sign in and bad state in Lichess TV

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#218]
I built the app and attempted to sign in. After being redirected to the website and authorizing the app (As I am logged already in in my browser), the sign in fails with this error:
```
I/flutter (14272): GET https://lichess.org/api/account
[AuthClient] GET https://lichess.org/api/account
             {Authorization: Bearer /* I don't know if this is sensible*/, user-agent: Lichess/0.2.0 ...
I/flutter (14272): GET https://lichess.org/api/account responded with status 401
I/flutter (14272): {"error":"No such token"}
[AuthClient] GET https://lichess.org/api/account responded with status 401
{"error":"No such token"}
I/flutter (14272): GET https://lichess.org/api/tv/feed
[AuthClient] GET https://lichess.org/api/tv/feed
             {user-agent: Lichess/0.2.0 TargetPlatform.android anon.}
```

After attempting and failing to sign in, I get this error on every move made in the Lichess TV:

```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to call `requireValue` on an `AsyncValue` that has no value: AsyncLoading<FeaturedGameState>()```

I am using Lineage OS 20 (Android 13) one a OnePlus 6T. The Viewer appears to be fully functional.

The Lichess TV appears to be thrown from this function (Full stacktrace below):
```Dart
void _onFenEvent(TvFenEvent event) {
    if (withSound) {
      ref.read(soundServiceProvider).play(Sound.move);
    }
    // TvFeaturedEvent is always emitted first so we can safely assume that
    // at this point the state is loaded.
    final game = state.requireValue; // <---- Thrown from here
    state = AsyncData(
      game.copyWith(
        white: game.white.withSeconds(event.whiteSeconds),
        black: game.black.withSeconds(event.whiteSeconds),
        position: FeaturedPosition.fromTvEvent(event),
      ),
    );
  }
}
```

Steps to reproduce:
 - Build the app
 - Attempt to sign in through the lichess.org authorization
 - Sign in should fail and the error messages from lichess TV should be thrown

Lichess TV should still be functional.

```
E/flutter (14272): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to call `requireValue` on an `AsyncValue` that has no value: AsyncLoading<FeaturedGameState>()
E/flutter (14272): #0      AsyncValueX.requireValue (package:riverpod/src/common.dart:501:5)
E/flutter (14272): #1      FeaturedGame._onFenEvent (package:lichess_mobile/src/model/tv/featured_game.dart:89:24)
E/flutter (14272): #2      FeaturedGame._connectStream.<anonymous closure> (package:lichess_mobile/src/model/tv/featured_game.dart:59:9)
E/flutter (14272): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #6      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
E/flutter (14272): #7      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (14272): #8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
E/flutter (14272): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (14272): #13     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (14272): #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #20     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14272): #21     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (14272): #22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #25     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14272): #26     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (14272): #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #30     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14272): #31     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter (14272): #32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #35     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (14272): #36     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (14272): #37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (14272): #41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (14272): #42     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
E/flutter (14272): #43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
E/flutter (14272): #44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
E/flutter (14272): #45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
E/flutter (14272): #46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
E/flutter (14272): #47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (14272): #48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #51     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #54     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (14272): #58     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (14272): #59     _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter (14272): #60     _HttpParser._doParse (dart:_http/http_parser.dart:829:28)
E/flutter (14272): #61     _HttpParser._parse (dart:_http/http_parser.dart:319:7)
E/flutter (14272): #62     _HttpParser._onData (dart:_http/http_parser.dart:873:5)
E/flutter (14272): #63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #66     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (14272): #67     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (14272): #68     _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter (14272): #69     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
E/flutter (14272): #70     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (14272): #71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (14272): #72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (14272): #73     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (14272): #74     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (14272): #75     _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter (14272): #76     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1114:19)
E/flutter (14272): #77     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (14272): #78     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (14272): #79     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (14272): #80     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by tedzards509** [comment]
After hard rebuilding, deleting all app data and deleting all API keys from my account, I cannot anymore reproduce the Lichess TV bug. I am assuming the "no such token" issue itself is a lichess API issue as I can see the token for org.lichess.mobile has been generated and associated with my account, but never used. Feel free to close if I am not mistaken.

**Comment by tedzards509** [comment]
The sign-in 401 issue is due to a server-side security change, according to veloce (https://discord.com/channels/280713822073913354/807722604478988348/1122866273638940712). So a local lila instance needs to be hosted.

As for the TV bug, veloce recommends to no spend time on it, as the Websocket API should replace the current TV backend (https://discord.com/channels/280713822073913354/807722604478988348/1122867713560293486).

**Comment by tedzards509** [comment]
Misclick
